export const DataNewFeed = [
    {
        id: 1,
        avatar: require('../assets/1.jpg'),
        title: "Bai dang 1",
        image:  require('../assets/1.jpg'),
        likeCount: 1,
        timeCreate: 1,
    },
    {
        id: 2,
        avatar: require('../assets/2.jpg'),
        title: "Bai dang 2",
        image:  require('../assets/2.jpg'),
        likeCount: 2,
        timeCreate: 2,
    },
    {
        id: 3,
        avatar: require('../assets/3.jpg'),
        title: "Bai dang 3",
        image:  require('../assets/3.jpg'),
        likeCount: 3,
        timeCreate: 3,
    },
    {
        id: 4,
        avatar: require('../assets/4.jpg'),
        title: "Bai dang 4",
        image:  require('../assets/4.jpg'),
        likeCount: 4,
        timeCreate: 4,
    },
    {
        id: 5,
        avatar: require('../assets/5.jpg'),
        title: "Bai dang 5",
        image:  require('../assets/5.jpg'),
        likeCount: 5,
        timeCreate: 5,
    },
    {
        id: 6,
        avatar: require('../assets/6.jpg'),
        title: "Bai dang 6",
        image:  require('../assets/6.jpg'),
        likeCount: 6,
        timeCreate: 6,
    },
]